// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/v3/sat.proto

#include "api/v3/sat.pb.h"
#include "api/v3/sat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace orbit {

static const char* PropagationService_method_names[] = {
  "/orbit.PropagationService/GetPropagation",
};

std::unique_ptr< PropagationService::Stub> PropagationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PropagationService::Stub> stub(new PropagationService::Stub(channel, options));
  return stub;
}

PropagationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetPropagation_(PropagationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PropagationService::Stub::GetPropagation(::grpc::ClientContext* context, const ::orbit::GetPropagationRequest& request, ::orbit::GetPropagationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::orbit::GetPropagationRequest, ::orbit::GetPropagationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPropagation_, context, request, response);
}

void PropagationService::Stub::async::GetPropagation(::grpc::ClientContext* context, const ::orbit::GetPropagationRequest* request, ::orbit::GetPropagationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::orbit::GetPropagationRequest, ::orbit::GetPropagationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropagation_, context, request, response, std::move(f));
}

void PropagationService::Stub::async::GetPropagation(::grpc::ClientContext* context, const ::orbit::GetPropagationRequest* request, ::orbit::GetPropagationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropagation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::orbit::GetPropagationResponse>* PropagationService::Stub::PrepareAsyncGetPropagationRaw(::grpc::ClientContext* context, const ::orbit::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::orbit::GetPropagationResponse, ::orbit::GetPropagationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPropagation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::orbit::GetPropagationResponse>* PropagationService::Stub::AsyncGetPropagationRaw(::grpc::ClientContext* context, const ::orbit::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPropagationRaw(context, request, cq);
  result->StartCall();
  return result;
}

PropagationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PropagationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PropagationService::Service, ::orbit::GetPropagationRequest, ::orbit::GetPropagationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PropagationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::orbit::GetPropagationRequest* req,
             ::orbit::GetPropagationResponse* resp) {
               return service->GetPropagation(ctx, req, resp);
             }, this)));
}

PropagationService::Service::~Service() {
}

::grpc::Status PropagationService::Service::GetPropagation(::grpc::ServerContext* context, const ::orbit::GetPropagationRequest* request, ::orbit::GetPropagationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace orbit
#include <grpcpp/ports_undef.inc>

