// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/v3/sat.proto
#ifndef GRPC_api_2fv3_2fsat_2eproto__INCLUDED
#define GRPC_api_2fv3_2fsat_2eproto__INCLUDED

#include "api/v3/sat.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace api {
namespace v3 {

class PropagationService final {
 public:
  static constexpr char const* service_full_name() {
    return "api.v3.PropagationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::api::v3::GetPropagationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>> AsyncGetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>>(AsyncGetPropagationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>> PrepareAsyncGetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>>(PrepareAsyncGetPropagationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>* AsyncGetPropagationRaw(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::v3::GetPropagationResponse>* PrepareAsyncGetPropagationRaw(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::api::v3::GetPropagationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>> AsyncGetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>>(AsyncGetPropagationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>> PrepareAsyncGetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>>(PrepareAsyncGetPropagationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPropagation(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>* AsyncGetPropagationRaw(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::v3::GetPropagationResponse>* PrepareAsyncGetPropagationRaw(::grpc::ClientContext* context, const ::api::v3::GetPropagationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPropagation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPropagation(::grpc::ServerContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPropagation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPropagation(::grpc::ServerContext* context, ::api::v3::GetPropagationRequest* request, ::grpc::ServerAsyncResponseWriter< ::api::v3::GetPropagationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPropagation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPropagation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::api::v3::GetPropagationRequest, ::api::v3::GetPropagationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::api::v3::GetPropagationRequest* request, ::api::v3::GetPropagationResponse* response) { return this->GetPropagation(context, request, response); }));}
    void SetMessageAllocatorFor_GetPropagation(
        ::grpc::MessageAllocator< ::api::v3::GetPropagationRequest, ::api::v3::GetPropagationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::api::v3::GetPropagationRequest, ::api::v3::GetPropagationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPropagation(
      ::grpc::CallbackServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetPropagation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPropagation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPropagation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPropagation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPropagation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPropagation(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPropagation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPropagation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPropagation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::api::v3::GetPropagationRequest, ::api::v3::GetPropagationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::api::v3::GetPropagationRequest, ::api::v3::GetPropagationResponse>* streamer) {
                       return this->StreamedGetPropagation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPropagation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPropagation(::grpc::ServerContext* /*context*/, const ::api::v3::GetPropagationRequest* /*request*/, ::api::v3::GetPropagationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPropagation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::api::v3::GetPropagationRequest,::api::v3::GetPropagationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPropagation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPropagation<Service > StreamedService;
};

}  // namespace v3
}  // namespace api


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_api_2fv3_2fsat_2eproto__INCLUDED
