// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v2/sat.proto
// Protobuf C++ Version: 6.31.1

#include "api/v2/sat.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace satproto {

inline constexpr PropogationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        norad_category_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PropogationRequest::PropogationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PropogationRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PropogationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PropogationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PropogationRequestDefaultTypeInternal() {}
  union {
    PropogationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PropogationRequestDefaultTypeInternal _PropogationRequest_default_instance_;

inline constexpr Propogation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_{::int64_t{0}},
        latitude_{0},
        longitude_{0},
        altitude_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Propogation::Propogation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Propogation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PropogationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PropogationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PropogationDefaultTypeInternal() {}
  union {
    Propogation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PropogationDefaultTypeInternal _Propogation_default_instance_;

inline constexpr Tle::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        line1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        line2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        propogation_{nullptr},
        age_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Tle::Tle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Tle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TleDefaultTypeInternal() {}
  union {
    Tle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TleDefaultTypeInternal _Tle_default_instance_;

inline constexpr PropogationReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        propogations_{},
        tle_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PropogationReply::PropogationReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PropogationReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PropogationReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PropogationReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PropogationReplyDefaultTypeInternal() {}
  union {
    PropogationReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PropogationReplyDefaultTypeInternal _PropogationReply_default_instance_;
}  // namespace satproto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_api_2fv2_2fsat_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_api_2fv2_2fsat_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2fv2_2fsat_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satproto::PropogationRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satproto::PropogationRequest, _impl_.norad_category_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satproto::PropogationReply, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satproto::PropogationReply, _impl_.tle_),
        PROTOBUF_FIELD_OFFSET(::satproto::PropogationReply, _impl_.propogations_),
        0,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_.line1_),
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_.line2_),
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_.age_),
        PROTOBUF_FIELD_OFFSET(::satproto::Tle, _impl_.propogation_),
        0,
        1,
        2,
        4,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satproto::Propogation, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satproto::Propogation, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::satproto::Propogation, _impl_.latitude_),
        PROTOBUF_FIELD_OFFSET(::satproto::Propogation, _impl_.longitude_),
        PROTOBUF_FIELD_OFFSET(::satproto::Propogation, _impl_.altitude_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::satproto::PropogationRequest)},
        {5, sizeof(::satproto::PropogationReply)},
        {12, sizeof(::satproto::Tle)},
        {25, sizeof(::satproto::Propogation)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::satproto::_PropogationRequest_default_instance_._instance,
    &::satproto::_PropogationReply_default_instance_._instance,
    &::satproto::_Tle_default_instance_._instance,
    &::satproto::_Propogation_default_instance_._instance,
};
const char descriptor_table_protodef_api_2fv2_2fsat_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020api/v2/sat.proto\022\010satproto\",\n\022Propogat"
    "ionRequest\022\026\n\016norad_category\030\001 \001(\005\"[\n\020Pr"
    "opogationReply\022\032\n\003tle\030\001 \001(\0132\r.satproto.T"
    "le\022+\n\014propogations\030\002 \003(\0132\025.satproto.Prop"
    "ogation\"j\n\003Tle\022\014\n\004name\030\001 \001(\t\022\r\n\005line1\030\002 "
    "\001(\t\022\r\n\005line2\030\003 \001(\t\022\013\n\003age\030\004 \001(\002\022*\n\013propo"
    "gation\030\005 \001(\0132\025.satproto.Propogation\"W\n\013P"
    "ropogation\022\021\n\ttimestamp\030\001 \001(\003\022\020\n\010latitud"
    "e\030\002 \001(\001\022\021\n\tlongitude\030\003 \001(\001\022\020\n\010altitude\030\004"
    " \001(\0022`\n\022PropogationService\022J\n\016GetPropoga"
    "tion\022\034.satproto.PropogationRequest\032\032.sat"
    "proto.PropogationReplyB\027Z\025include/satpos"
    "/api/v1b\006proto3"
};
static ::absl::once_flag descriptor_table_api_2fv2_2fsat_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2fv2_2fsat_2eproto = {
    false,
    false,
    495,
    descriptor_table_protodef_api_2fv2_2fsat_2eproto,
    "api/v2/sat.proto",
    &descriptor_table_api_2fv2_2fsat_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_api_2fv2_2fsat_2eproto::offsets,
    file_level_enum_descriptors_api_2fv2_2fsat_2eproto,
    file_level_service_descriptors_api_2fv2_2fsat_2eproto,
};
namespace satproto {
// ===================================================================

class PropogationRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PropogationRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PropogationRequest, _impl_._has_bits_);
};

PropogationRequest::PropogationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PropogationRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satproto.PropogationRequest)
}
PropogationRequest::PropogationRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PropogationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PropogationRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PropogationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PropogationRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.norad_category_ = {};
}
PropogationRequest::~PropogationRequest() {
  // @@protoc_insertion_point(destructor:satproto.PropogationRequest)
  SharedDtor(*this);
}
inline void PropogationRequest::SharedDtor(MessageLite& self) {
  PropogationRequest& this_ = static_cast<PropogationRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PropogationRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PropogationRequest(arena);
}
constexpr auto PropogationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PropogationRequest),
                                            alignof(PropogationRequest));
}
constexpr auto PropogationRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PropogationRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PropogationRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PropogationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PropogationRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PropogationRequest>(), &PropogationRequest::ByteSizeLong,
              &PropogationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PropogationRequest, _impl_._cached_size_),
          false,
      },
      &PropogationRequest::kDescriptorMethods,
      &descriptor_table_api_2fv2_2fsat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PropogationRequest_class_data_ =
        PropogationRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PropogationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PropogationRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PropogationRequest_class_data_.tc_table);
  return PropogationRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PropogationRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PropogationRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PropogationRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satproto::PropogationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 norad_category = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PropogationRequest, _impl_.norad_category_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PropogationRequest, _impl_.norad_category_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 norad_category = 1;
    {PROTOBUF_FIELD_OFFSET(PropogationRequest, _impl_.norad_category_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PropogationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:satproto.PropogationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.norad_category_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PropogationRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PropogationRequest& this_ = static_cast<const PropogationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PropogationRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PropogationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satproto.PropogationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 norad_category = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_norad_category() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_norad_category(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satproto.PropogationRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PropogationRequest::ByteSizeLong(const MessageLite& base) {
  const PropogationRequest& this_ = static_cast<const PropogationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PropogationRequest::ByteSizeLong() const {
  const PropogationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satproto.PropogationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 norad_category = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_norad_category() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_norad_category());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PropogationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PropogationRequest*>(&to_msg);
  auto& from = static_cast<const PropogationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satproto.PropogationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_norad_category() != 0) {
      _this->_impl_.norad_category_ = from._impl_.norad_category_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PropogationRequest::CopyFrom(const PropogationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satproto.PropogationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PropogationRequest::InternalSwap(PropogationRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.norad_category_, other->_impl_.norad_category_);
}

::google::protobuf::Metadata PropogationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PropogationReply::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PropogationReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_._has_bits_);
};

PropogationReply::PropogationReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PropogationReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satproto.PropogationReply)
}
PROTOBUF_NDEBUG_INLINE PropogationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::satproto::PropogationReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        propogations_{visibility, arena, from.propogations_} {}

PropogationReply::PropogationReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PropogationReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PropogationReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PropogationReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.tle_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.tle_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:satproto.PropogationReply)
}
PROTOBUF_NDEBUG_INLINE PropogationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        propogations_{visibility, arena} {}

inline void PropogationReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.tle_ = {};
}
PropogationReply::~PropogationReply() {
  // @@protoc_insertion_point(destructor:satproto.PropogationReply)
  SharedDtor(*this);
}
inline void PropogationReply::SharedDtor(MessageLite& self) {
  PropogationReply& this_ = static_cast<PropogationReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.tle_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PropogationReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PropogationReply(arena);
}
constexpr auto PropogationReply::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_.propogations_) +
          decltype(PropogationReply::_impl_.propogations_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PropogationReply), alignof(PropogationReply), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PropogationReply::PlacementNew_,
                                 sizeof(PropogationReply),
                                 alignof(PropogationReply));
  }
}
constexpr auto PropogationReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PropogationReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PropogationReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PropogationReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PropogationReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PropogationReply>(), &PropogationReply::ByteSizeLong,
              &PropogationReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_._cached_size_),
          false,
      },
      &PropogationReply::kDescriptorMethods,
      &descriptor_table_api_2fv2_2fsat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PropogationReply_class_data_ =
        PropogationReply::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PropogationReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PropogationReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PropogationReply_class_data_.tc_table);
  return PropogationReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
PropogationReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PropogationReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satproto::PropogationReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .satproto.Propogation propogations = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_.propogations_)}},
    // .satproto.Tle tle = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_.tle_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .satproto.Tle tle = 1;
    {PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_.tle_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .satproto.Propogation propogations = 2;
    {PROTOBUF_FIELD_OFFSET(PropogationReply, _impl_.propogations_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::satproto::Tle>()},
      {::_pbi::TcParser::GetTable<::satproto::Propogation>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PropogationReply::Clear() {
// @@protoc_insertion_point(message_clear_start:satproto.PropogationReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.propogations_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.tle_ != nullptr);
    _impl_.tle_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PropogationReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PropogationReply& this_ = static_cast<const PropogationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PropogationReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PropogationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satproto.PropogationReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .satproto.Tle tle = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.tle_, this_._impl_.tle_->GetCachedSize(), target,
        stream);
  }

  // repeated .satproto.Propogation propogations = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_propogations_size());
       i < n; i++) {
    const auto& repfield = this_._internal_propogations().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satproto.PropogationReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PropogationReply::ByteSizeLong(const MessageLite& base) {
  const PropogationReply& this_ = static_cast<const PropogationReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PropogationReply::ByteSizeLong() const {
  const PropogationReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satproto.PropogationReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .satproto.Propogation propogations = 2;
    {
      total_size += 1UL * this_._internal_propogations_size();
      for (const auto& msg : this_._internal_propogations()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // .satproto.Tle tle = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.tle_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PropogationReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PropogationReply*>(&to_msg);
  auto& from = static_cast<const PropogationReply&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:satproto.PropogationReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_propogations()->MergeFrom(
      from._internal_propogations());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(from._impl_.tle_ != nullptr);
    if (_this->_impl_.tle_ == nullptr) {
      _this->_impl_.tle_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.tle_);
    } else {
      _this->_impl_.tle_->MergeFrom(*from._impl_.tle_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PropogationReply::CopyFrom(const PropogationReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satproto.PropogationReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PropogationReply::InternalSwap(PropogationReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.propogations_.InternalSwap(&other->_impl_.propogations_);
  swap(_impl_.tle_, other->_impl_.tle_);
}

::google::protobuf::Metadata PropogationReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Tle::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tle>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tle, _impl_._has_bits_);
};

Tle::Tle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Tle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satproto.Tle)
}
PROTOBUF_NDEBUG_INLINE Tle::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::satproto::Tle& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        line1_(arena, from.line1_),
        line2_(arena, from.line2_) {}

Tle::Tle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Tle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Tle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.propogation_ = ((cached_has_bits & 0x00000008u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.propogation_)
                : nullptr;
  _impl_.age_ = from._impl_.age_;

  // @@protoc_insertion_point(copy_constructor:satproto.Tle)
}
PROTOBUF_NDEBUG_INLINE Tle::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        line1_(arena),
        line2_(arena) {}

inline void Tle::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, propogation_),
           0,
           offsetof(Impl_, age_) -
               offsetof(Impl_, propogation_) +
               sizeof(Impl_::age_));
}
Tle::~Tle() {
  // @@protoc_insertion_point(destructor:satproto.Tle)
  SharedDtor(*this);
}
inline void Tle::SharedDtor(MessageLite& self) {
  Tle& this_ = static_cast<Tle&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.line1_.Destroy();
  this_._impl_.line2_.Destroy();
  delete this_._impl_.propogation_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tle(arena);
}
constexpr auto Tle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Tle),
                                            alignof(Tle));
}
constexpr auto Tle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Tle_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Tle::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Tle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tle::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Tle>(), &Tle::ByteSizeLong,
              &Tle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tle, _impl_._cached_size_),
          false,
      },
      &Tle::kDescriptorMethods,
      &descriptor_table_api_2fv2_2fsat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Tle_class_data_ =
        Tle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Tle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Tle_class_data_.tc_table);
  return Tle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 35, 2>
Tle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tle, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Tle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satproto::Tle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Tle, _impl_.name_)}},
    // string line1 = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Tle, _impl_.line1_)}},
    // string line2 = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(Tle, _impl_.line2_)}},
    // float age = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 4, 0, PROTOBUF_FIELD_OFFSET(Tle, _impl_.age_)}},
    // .satproto.Propogation propogation = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 3, 0, PROTOBUF_FIELD_OFFSET(Tle, _impl_.propogation_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Tle, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string line1 = 2;
    {PROTOBUF_FIELD_OFFSET(Tle, _impl_.line1_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string line2 = 3;
    {PROTOBUF_FIELD_OFFSET(Tle, _impl_.line2_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float age = 4;
    {PROTOBUF_FIELD_OFFSET(Tle, _impl_.age_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .satproto.Propogation propogation = 5;
    {PROTOBUF_FIELD_OFFSET(Tle, _impl_.propogation_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::satproto::Propogation>()},
  }},
  {{
    "\14\4\5\5\0\0\0\0"
    "satproto.Tle"
    "name"
    "line1"
    "line2"
  }},
};
PROTOBUF_NOINLINE void Tle::Clear() {
// @@protoc_insertion_point(message_clear_start:satproto.Tle)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.line1_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.line2_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(_impl_.propogation_ != nullptr);
      _impl_.propogation_->Clear();
    }
  }
  _impl_.age_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tle::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tle& this_ = static_cast<const Tle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tle::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satproto.Tle)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satproto.Tle.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string line1 = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_line1().empty()) {
      const ::std::string& _s = this_._internal_line1();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satproto.Tle.line1");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string line2 = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_line2().empty()) {
      const ::std::string& _s = this_._internal_line2();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satproto.Tle.line2");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // float age = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_age()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_age(), target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .satproto.Propogation propogation = 5;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.propogation_, this_._impl_.propogation_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satproto.Tle)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tle::ByteSizeLong(const MessageLite& base) {
  const Tle& this_ = static_cast<const Tle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tle::ByteSizeLong() const {
  const Tle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satproto.Tle)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // string name = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string line1 = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_line1().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_line1());
      }
    }
    // string line2 = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_line2().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_line2());
      }
    }
    // .satproto.Propogation propogation = 5;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.propogation_);
    }
    // float age = 4;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_age()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Tle::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tle*>(&to_msg);
  auto& from = static_cast<const Tle&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:satproto.Tle)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_line1().empty()) {
        _this->_internal_set_line1(from._internal_line1());
      } else {
        if (_this->_impl_.line1_.IsDefault()) {
          _this->_internal_set_line1("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_line2().empty()) {
        _this->_internal_set_line2(from._internal_line2());
      } else {
        if (_this->_impl_.line2_.IsDefault()) {
          _this->_internal_set_line2("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(from._impl_.propogation_ != nullptr);
      if (_this->_impl_.propogation_ == nullptr) {
        _this->_impl_.propogation_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.propogation_);
      } else {
        _this->_impl_.propogation_->MergeFrom(*from._impl_.propogation_);
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_age()) != 0) {
        _this->_impl_.age_ = from._impl_.age_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tle::CopyFrom(const Tle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satproto.Tle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Tle::InternalSwap(Tle* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.line1_, &other->_impl_.line1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.line2_, &other->_impl_.line2_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tle, _impl_.age_)
      + sizeof(Tle::_impl_.age_)
      - PROTOBUF_FIELD_OFFSET(Tle, _impl_.propogation_)>(
          reinterpret_cast<char*>(&_impl_.propogation_),
          reinterpret_cast<char*>(&other->_impl_.propogation_));
}

::google::protobuf::Metadata Tle::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Propogation::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Propogation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Propogation, _impl_._has_bits_);
};

Propogation::Propogation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Propogation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satproto.Propogation)
}
Propogation::Propogation(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Propogation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Propogation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Propogation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Propogation::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, altitude_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::altitude_));
}
Propogation::~Propogation() {
  // @@protoc_insertion_point(destructor:satproto.Propogation)
  SharedDtor(*this);
}
inline void Propogation::SharedDtor(MessageLite& self) {
  Propogation& this_ = static_cast<Propogation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Propogation::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Propogation(arena);
}
constexpr auto Propogation::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Propogation),
                                            alignof(Propogation));
}
constexpr auto Propogation::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Propogation_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Propogation::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Propogation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Propogation::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Propogation>(), &Propogation::ByteSizeLong,
              &Propogation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Propogation, _impl_._cached_size_),
          false,
      },
      &Propogation::kDescriptorMethods,
      &descriptor_table_api_2fv2_2fsat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Propogation_class_data_ =
        Propogation::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Propogation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Propogation_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Propogation_class_data_.tc_table);
  return Propogation_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
Propogation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Propogation, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Propogation_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satproto::Propogation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float altitude = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(Propogation, _impl_.altitude_)}},
    // int64 timestamp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Propogation, _impl_.timestamp_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Propogation, _impl_.timestamp_)}},
    // double latitude = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0, PROTOBUF_FIELD_OFFSET(Propogation, _impl_.latitude_)}},
    // double longitude = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0, PROTOBUF_FIELD_OFFSET(Propogation, _impl_.longitude_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(Propogation, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // double latitude = 2;
    {PROTOBUF_FIELD_OFFSET(Propogation, _impl_.latitude_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double longitude = 3;
    {PROTOBUF_FIELD_OFFSET(Propogation, _impl_.longitude_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // float altitude = 4;
    {PROTOBUF_FIELD_OFFSET(Propogation, _impl_.altitude_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Propogation::Clear() {
// @@protoc_insertion_point(message_clear_start:satproto.Propogation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.altitude_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.altitude_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Propogation::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Propogation& this_ = static_cast<const Propogation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Propogation::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Propogation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satproto.Propogation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 timestamp = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_timestamp(), target);
    }
  }

  // double latitude = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_latitude()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_latitude(), target);
    }
  }

  // double longitude = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_longitude()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_longitude(), target);
    }
  }

  // float altitude = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_altitude()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_altitude(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satproto.Propogation)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Propogation::ByteSizeLong(const MessageLite& base) {
  const Propogation& this_ = static_cast<const Propogation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Propogation::ByteSizeLong() const {
  const Propogation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satproto.Propogation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // int64 timestamp = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // double latitude = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_latitude()) != 0) {
        total_size += 9;
      }
    }
    // double longitude = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_longitude()) != 0) {
        total_size += 9;
      }
    }
    // float altitude = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_altitude()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Propogation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Propogation*>(&to_msg);
  auto& from = static_cast<const Propogation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satproto.Propogation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_latitude()) != 0) {
        _this->_impl_.latitude_ = from._impl_.latitude_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_longitude()) != 0) {
        _this->_impl_.longitude_ = from._impl_.longitude_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_altitude()) != 0) {
        _this->_impl_.altitude_ = from._impl_.altitude_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Propogation::CopyFrom(const Propogation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satproto.Propogation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Propogation::InternalSwap(Propogation* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Propogation, _impl_.altitude_)
      + sizeof(Propogation::_impl_.altitude_)
      - PROTOBUF_FIELD_OFFSET(Propogation, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata Propogation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace satproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_api_2fv2_2fsat_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
