// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v2/sat.proto
// Protobuf C++ Version: 6.31.1

#ifndef api_2fv2_2fsat_2eproto_2epb_2eh
#define api_2fv2_2fsat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_2fv2_2fsat_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_2fv2_2fsat_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_api_2fv2_2fsat_2eproto;
}  // extern "C"
namespace satproto {
class Propogation;
struct PropogationDefaultTypeInternal;
extern PropogationDefaultTypeInternal _Propogation_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Propogation_class_data_;
class PropogationReply;
struct PropogationReplyDefaultTypeInternal;
extern PropogationReplyDefaultTypeInternal _PropogationReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PropogationReply_class_data_;
class PropogationRequest;
struct PropogationRequestDefaultTypeInternal;
extern PropogationRequestDefaultTypeInternal _PropogationRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PropogationRequest_class_data_;
class Tle;
struct TleDefaultTypeInternal;
extern TleDefaultTypeInternal _Tle_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Tle_class_data_;
}  // namespace satproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace satproto {

// ===================================================================


// -------------------------------------------------------------------

class PropogationRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satproto.PropogationRequest) */ {
 public:
  inline PropogationRequest() : PropogationRequest(nullptr) {}
  ~PropogationRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PropogationRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PropogationRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PropogationRequest(::google::protobuf::internal::ConstantInitialized);

  inline PropogationRequest(const PropogationRequest& from) : PropogationRequest(nullptr, from) {}
  inline PropogationRequest(PropogationRequest&& from) noexcept
      : PropogationRequest(nullptr, ::std::move(from)) {}
  inline PropogationRequest& operator=(const PropogationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PropogationRequest& operator=(PropogationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PropogationRequest& default_instance() {
    return *reinterpret_cast<const PropogationRequest*>(
        &_PropogationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PropogationRequest& a, PropogationRequest& b) { a.Swap(&b); }
  inline void Swap(PropogationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PropogationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PropogationRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PropogationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PropogationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PropogationRequest& from) { PropogationRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PropogationRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satproto.PropogationRequest"; }

 protected:
  explicit PropogationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PropogationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PropogationRequest& from);
  PropogationRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PropogationRequest&& from) noexcept
      : PropogationRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNoradCategoryFieldNumber = 1,
  };
  // int32 norad_category = 1;
  void clear_norad_category() ;
  ::int32_t norad_category() const;
  void set_norad_category(::int32_t value);

  private:
  ::int32_t _internal_norad_category() const;
  void _internal_set_norad_category(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:satproto.PropogationRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PropogationRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t norad_category_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fv2_2fsat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PropogationRequest_class_data_;
// -------------------------------------------------------------------

class Propogation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satproto.Propogation) */ {
 public:
  inline Propogation() : Propogation(nullptr) {}
  ~Propogation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Propogation* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Propogation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Propogation(::google::protobuf::internal::ConstantInitialized);

  inline Propogation(const Propogation& from) : Propogation(nullptr, from) {}
  inline Propogation(Propogation&& from) noexcept
      : Propogation(nullptr, ::std::move(from)) {}
  inline Propogation& operator=(const Propogation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Propogation& operator=(Propogation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Propogation& default_instance() {
    return *reinterpret_cast<const Propogation*>(
        &_Propogation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Propogation& a, Propogation& b) { a.Swap(&b); }
  inline void Swap(Propogation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Propogation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Propogation* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Propogation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Propogation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Propogation& from) { Propogation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Propogation* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satproto.Propogation"; }

 protected:
  explicit Propogation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Propogation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Propogation& from);
  Propogation(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Propogation&& from) noexcept
      : Propogation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampFieldNumber = 1,
    kLatitudeFieldNumber = 2,
    kLongitudeFieldNumber = 3,
    kAltitudeFieldNumber = 4,
  };
  // int64 timestamp = 1;
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // double latitude = 2;
  void clear_latitude() ;
  double latitude() const;
  void set_latitude(double value);

  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);

  public:
  // double longitude = 3;
  void clear_longitude() ;
  double longitude() const;
  void set_longitude(double value);

  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);

  public:
  // float altitude = 4;
  void clear_altitude() ;
  float altitude() const;
  void set_altitude(float value);

  private:
  float _internal_altitude() const;
  void _internal_set_altitude(float value);

  public:
  // @@protoc_insertion_point(class_scope:satproto.Propogation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Propogation& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t timestamp_;
    double latitude_;
    double longitude_;
    float altitude_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fv2_2fsat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Propogation_class_data_;
// -------------------------------------------------------------------

class Tle final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satproto.Tle) */ {
 public:
  inline Tle() : Tle(nullptr) {}
  ~Tle() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Tle* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Tle));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Tle(::google::protobuf::internal::ConstantInitialized);

  inline Tle(const Tle& from) : Tle(nullptr, from) {}
  inline Tle(Tle&& from) noexcept
      : Tle(nullptr, ::std::move(from)) {}
  inline Tle& operator=(const Tle& from) {
    CopyFrom(from);
    return *this;
  }
  inline Tle& operator=(Tle&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Tle& default_instance() {
    return *reinterpret_cast<const Tle*>(
        &_Tle_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Tle& a, Tle& b) { a.Swap(&b); }
  inline void Swap(Tle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Tle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Tle* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Tle>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Tle& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Tle& from) { Tle::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Tle* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satproto.Tle"; }

 protected:
  explicit Tle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Tle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Tle& from);
  Tle(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Tle&& from) noexcept
      : Tle(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kLine1FieldNumber = 2,
    kLine2FieldNumber = 3,
    kPropogationFieldNumber = 5,
    kAgeFieldNumber = 4,
  };
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string line1 = 2;
  void clear_line1() ;
  const ::std::string& line1() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_line1(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_line1();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_line1();
  void set_allocated_line1(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_line1() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_line1(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_line1();

  public:
  // string line2 = 3;
  void clear_line2() ;
  const ::std::string& line2() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_line2(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_line2();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_line2();
  void set_allocated_line2(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_line2() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_line2(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_line2();

  public:
  // .satproto.Propogation propogation = 5;
  bool has_propogation() const;
  void clear_propogation() ;
  const ::satproto::Propogation& propogation() const;
  [[nodiscard]] ::satproto::Propogation* PROTOBUF_NULLABLE release_propogation();
  ::satproto::Propogation* PROTOBUF_NONNULL mutable_propogation();
  void set_allocated_propogation(::satproto::Propogation* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_propogation(::satproto::Propogation* PROTOBUF_NULLABLE value);
  ::satproto::Propogation* PROTOBUF_NULLABLE unsafe_arena_release_propogation();

  private:
  const ::satproto::Propogation& _internal_propogation() const;
  ::satproto::Propogation* PROTOBUF_NONNULL _internal_mutable_propogation();

  public:
  // float age = 4;
  void clear_age() ;
  float age() const;
  void set_age(float value);

  private:
  float _internal_age() const;
  void _internal_set_age(float value);

  public:
  // @@protoc_insertion_point(class_scope:satproto.Tle)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   1, 35,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Tle& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr line1_;
    ::google::protobuf::internal::ArenaStringPtr line2_;
    ::satproto::Propogation* PROTOBUF_NULLABLE propogation_;
    float age_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fv2_2fsat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Tle_class_data_;
// -------------------------------------------------------------------

class PropogationReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satproto.PropogationReply) */ {
 public:
  inline PropogationReply() : PropogationReply(nullptr) {}
  ~PropogationReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PropogationReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PropogationReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PropogationReply(::google::protobuf::internal::ConstantInitialized);

  inline PropogationReply(const PropogationReply& from) : PropogationReply(nullptr, from) {}
  inline PropogationReply(PropogationReply&& from) noexcept
      : PropogationReply(nullptr, ::std::move(from)) {}
  inline PropogationReply& operator=(const PropogationReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline PropogationReply& operator=(PropogationReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PropogationReply& default_instance() {
    return *reinterpret_cast<const PropogationReply*>(
        &_PropogationReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PropogationReply& a, PropogationReply& b) { a.Swap(&b); }
  inline void Swap(PropogationReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PropogationReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PropogationReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PropogationReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PropogationReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PropogationReply& from) { PropogationReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PropogationReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satproto.PropogationReply"; }

 protected:
  explicit PropogationReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PropogationReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PropogationReply& from);
  PropogationReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PropogationReply&& from) noexcept
      : PropogationReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPropogationsFieldNumber = 2,
    kTleFieldNumber = 1,
  };
  // repeated .satproto.Propogation propogations = 2;
  int propogations_size() const;
  private:
  int _internal_propogations_size() const;

  public:
  void clear_propogations() ;
  ::satproto::Propogation* PROTOBUF_NONNULL mutable_propogations(int index);
  ::google::protobuf::RepeatedPtrField<::satproto::Propogation>* PROTOBUF_NONNULL mutable_propogations();

  private:
  const ::google::protobuf::RepeatedPtrField<::satproto::Propogation>& _internal_propogations() const;
  ::google::protobuf::RepeatedPtrField<::satproto::Propogation>* PROTOBUF_NONNULL _internal_mutable_propogations();
  public:
  const ::satproto::Propogation& propogations(int index) const;
  ::satproto::Propogation* PROTOBUF_NONNULL add_propogations();
  const ::google::protobuf::RepeatedPtrField<::satproto::Propogation>& propogations() const;
  // .satproto.Tle tle = 1;
  bool has_tle() const;
  void clear_tle() ;
  const ::satproto::Tle& tle() const;
  [[nodiscard]] ::satproto::Tle* PROTOBUF_NULLABLE release_tle();
  ::satproto::Tle* PROTOBUF_NONNULL mutable_tle();
  void set_allocated_tle(::satproto::Tle* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_tle(::satproto::Tle* PROTOBUF_NULLABLE value);
  ::satproto::Tle* PROTOBUF_NULLABLE unsafe_arena_release_tle();

  private:
  const ::satproto::Tle& _internal_tle() const;
  ::satproto::Tle* PROTOBUF_NONNULL _internal_mutable_tle();

  public:
  // @@protoc_insertion_point(class_scope:satproto.PropogationReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PropogationReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::satproto::Propogation > propogations_;
    ::satproto::Tle* PROTOBUF_NULLABLE tle_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fv2_2fsat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PropogationReply_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PropogationRequest

// int32 norad_category = 1;
inline void PropogationRequest::clear_norad_category() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.norad_category_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PropogationRequest::norad_category() const {
  // @@protoc_insertion_point(field_get:satproto.PropogationRequest.norad_category)
  return _internal_norad_category();
}
inline void PropogationRequest::set_norad_category(::int32_t value) {
  _internal_set_norad_category(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:satproto.PropogationRequest.norad_category)
}
inline ::int32_t PropogationRequest::_internal_norad_category() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.norad_category_;
}
inline void PropogationRequest::_internal_set_norad_category(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.norad_category_ = value;
}

// -------------------------------------------------------------------

// PropogationReply

// .satproto.Tle tle = 1;
inline bool PropogationReply::has_tle() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.tle_ != nullptr);
  return value;
}
inline void PropogationReply::clear_tle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.tle_ != nullptr) _impl_.tle_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::satproto::Tle& PropogationReply::_internal_tle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::satproto::Tle* p = _impl_.tle_;
  return p != nullptr ? *p : reinterpret_cast<const ::satproto::Tle&>(::satproto::_Tle_default_instance_);
}
inline const ::satproto::Tle& PropogationReply::tle() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.PropogationReply.tle)
  return _internal_tle();
}
inline void PropogationReply::unsafe_arena_set_allocated_tle(
    ::satproto::Tle* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tle_);
  }
  _impl_.tle_ = reinterpret_cast<::satproto::Tle*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:satproto.PropogationReply.tle)
}
inline ::satproto::Tle* PROTOBUF_NULLABLE PropogationReply::release_tle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::satproto::Tle* released = _impl_.tle_;
  _impl_.tle_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::satproto::Tle* PROTOBUF_NULLABLE PropogationReply::unsafe_arena_release_tle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satproto.PropogationReply.tle)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::satproto::Tle* temp = _impl_.tle_;
  _impl_.tle_ = nullptr;
  return temp;
}
inline ::satproto::Tle* PROTOBUF_NONNULL PropogationReply::_internal_mutable_tle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.tle_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::satproto::Tle>(GetArena());
    _impl_.tle_ = reinterpret_cast<::satproto::Tle*>(p);
  }
  return _impl_.tle_;
}
inline ::satproto::Tle* PROTOBUF_NONNULL PropogationReply::mutable_tle()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::satproto::Tle* _msg = _internal_mutable_tle();
  // @@protoc_insertion_point(field_mutable:satproto.PropogationReply.tle)
  return _msg;
}
inline void PropogationReply::set_allocated_tle(::satproto::Tle* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tle_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.tle_ = reinterpret_cast<::satproto::Tle*>(value);
  // @@protoc_insertion_point(field_set_allocated:satproto.PropogationReply.tle)
}

// repeated .satproto.Propogation propogations = 2;
inline int PropogationReply::_internal_propogations_size() const {
  return _internal_propogations().size();
}
inline int PropogationReply::propogations_size() const {
  return _internal_propogations_size();
}
inline void PropogationReply::clear_propogations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.propogations_.Clear();
}
inline ::satproto::Propogation* PROTOBUF_NONNULL PropogationReply::mutable_propogations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:satproto.PropogationReply.propogations)
  return _internal_mutable_propogations()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::satproto::Propogation>* PROTOBUF_NONNULL PropogationReply::mutable_propogations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satproto.PropogationReply.propogations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_propogations();
}
inline const ::satproto::Propogation& PropogationReply::propogations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.PropogationReply.propogations)
  return _internal_propogations().Get(index);
}
inline ::satproto::Propogation* PROTOBUF_NONNULL PropogationReply::add_propogations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::satproto::Propogation* _add = _internal_mutable_propogations()->Add();
  // @@protoc_insertion_point(field_add:satproto.PropogationReply.propogations)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::satproto::Propogation>& PropogationReply::propogations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satproto.PropogationReply.propogations)
  return _internal_propogations();
}
inline const ::google::protobuf::RepeatedPtrField<::satproto::Propogation>&
PropogationReply::_internal_propogations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.propogations_;
}
inline ::google::protobuf::RepeatedPtrField<::satproto::Propogation>* PROTOBUF_NONNULL
PropogationReply::_internal_mutable_propogations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.propogations_;
}

// -------------------------------------------------------------------

// Tle

// string name = 1;
inline void Tle::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Tle::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.Tle.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Tle::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satproto.Tle.name)
}
inline ::std::string* PROTOBUF_NONNULL Tle::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:satproto.Tle.name)
  return _s;
}
inline const ::std::string& Tle::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Tle::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Tle::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Tle::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satproto.Tle.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void Tle::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satproto.Tle.name)
}

// string line1 = 2;
inline void Tle::clear_line1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line1_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& Tle::line1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.Tle.line1)
  return _internal_line1();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Tle::set_line1(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.line1_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satproto.Tle.line1)
}
inline ::std::string* PROTOBUF_NONNULL Tle::mutable_line1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_line1();
  // @@protoc_insertion_point(field_mutable:satproto.Tle.line1)
  return _s;
}
inline const ::std::string& Tle::_internal_line1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line1_.Get();
}
inline void Tle::_internal_set_line1(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.line1_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Tle::_internal_mutable_line1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.line1_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Tle::release_line1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satproto.Tle.line1)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.line1_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.line1_.Set("", GetArena());
  }
  return released;
}
inline void Tle::set_allocated_line1(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.line1_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.line1_.IsDefault()) {
    _impl_.line1_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satproto.Tle.line1)
}

// string line2 = 3;
inline void Tle::clear_line2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line2_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& Tle::line2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.Tle.line2)
  return _internal_line2();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Tle::set_line2(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.line2_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satproto.Tle.line2)
}
inline ::std::string* PROTOBUF_NONNULL Tle::mutable_line2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_line2();
  // @@protoc_insertion_point(field_mutable:satproto.Tle.line2)
  return _s;
}
inline const ::std::string& Tle::_internal_line2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line2_.Get();
}
inline void Tle::_internal_set_line2(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.line2_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Tle::_internal_mutable_line2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.line2_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Tle::release_line2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satproto.Tle.line2)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.line2_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.line2_.Set("", GetArena());
  }
  return released;
}
inline void Tle::set_allocated_line2(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.line2_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.line2_.IsDefault()) {
    _impl_.line2_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satproto.Tle.line2)
}

// float age = 4;
inline void Tle::clear_age() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.age_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float Tle::age() const {
  // @@protoc_insertion_point(field_get:satproto.Tle.age)
  return _internal_age();
}
inline void Tle::set_age(float value) {
  _internal_set_age(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:satproto.Tle.age)
}
inline float Tle::_internal_age() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.age_;
}
inline void Tle::_internal_set_age(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.age_ = value;
}

// .satproto.Propogation propogation = 5;
inline bool Tle::has_propogation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.propogation_ != nullptr);
  return value;
}
inline void Tle::clear_propogation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.propogation_ != nullptr) _impl_.propogation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::satproto::Propogation& Tle::_internal_propogation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::satproto::Propogation* p = _impl_.propogation_;
  return p != nullptr ? *p : reinterpret_cast<const ::satproto::Propogation&>(::satproto::_Propogation_default_instance_);
}
inline const ::satproto::Propogation& Tle::propogation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satproto.Tle.propogation)
  return _internal_propogation();
}
inline void Tle::unsafe_arena_set_allocated_propogation(
    ::satproto::Propogation* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.propogation_);
  }
  _impl_.propogation_ = reinterpret_cast<::satproto::Propogation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:satproto.Tle.propogation)
}
inline ::satproto::Propogation* PROTOBUF_NULLABLE Tle::release_propogation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::satproto::Propogation* released = _impl_.propogation_;
  _impl_.propogation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::satproto::Propogation* PROTOBUF_NULLABLE Tle::unsafe_arena_release_propogation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satproto.Tle.propogation)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::satproto::Propogation* temp = _impl_.propogation_;
  _impl_.propogation_ = nullptr;
  return temp;
}
inline ::satproto::Propogation* PROTOBUF_NONNULL Tle::_internal_mutable_propogation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.propogation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::satproto::Propogation>(GetArena());
    _impl_.propogation_ = reinterpret_cast<::satproto::Propogation*>(p);
  }
  return _impl_.propogation_;
}
inline ::satproto::Propogation* PROTOBUF_NONNULL Tle::mutable_propogation()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::satproto::Propogation* _msg = _internal_mutable_propogation();
  // @@protoc_insertion_point(field_mutable:satproto.Tle.propogation)
  return _msg;
}
inline void Tle::set_allocated_propogation(::satproto::Propogation* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.propogation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.propogation_ = reinterpret_cast<::satproto::Propogation*>(value);
  // @@protoc_insertion_point(field_set_allocated:satproto.Tle.propogation)
}

// -------------------------------------------------------------------

// Propogation

// int64 timestamp = 1;
inline void Propogation::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t Propogation::timestamp() const {
  // @@protoc_insertion_point(field_get:satproto.Propogation.timestamp)
  return _internal_timestamp();
}
inline void Propogation::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:satproto.Propogation.timestamp)
}
inline ::int64_t Propogation::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void Propogation::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// double latitude = 2;
inline void Propogation::clear_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double Propogation::latitude() const {
  // @@protoc_insertion_point(field_get:satproto.Propogation.latitude)
  return _internal_latitude();
}
inline void Propogation::set_latitude(double value) {
  _internal_set_latitude(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:satproto.Propogation.latitude)
}
inline double Propogation::_internal_latitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latitude_;
}
inline void Propogation::_internal_set_latitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = value;
}

// double longitude = 3;
inline void Propogation::clear_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double Propogation::longitude() const {
  // @@protoc_insertion_point(field_get:satproto.Propogation.longitude)
  return _internal_longitude();
}
inline void Propogation::set_longitude(double value) {
  _internal_set_longitude(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:satproto.Propogation.longitude)
}
inline double Propogation::_internal_longitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitude_;
}
inline void Propogation::_internal_set_longitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = value;
}

// float altitude = 4;
inline void Propogation::clear_altitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float Propogation::altitude() const {
  // @@protoc_insertion_point(field_get:satproto.Propogation.altitude)
  return _internal_altitude();
}
inline void Propogation::set_altitude(float value) {
  _internal_set_altitude(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:satproto.Propogation.altitude)
}
inline float Propogation::_internal_altitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.altitude_;
}
inline void Propogation::_internal_set_altitude(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace satproto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_2fv2_2fsat_2eproto_2epb_2eh
