// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/v2/sat.proto

#include "api/v2/sat.pb.h"
#include "api/v2/sat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace satproto {

static const char* PropogationService_method_names[] = {
  "/satproto.PropogationService/GetPropogation",
};

std::unique_ptr< PropogationService::Stub> PropogationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PropogationService::Stub> stub(new PropogationService::Stub(channel, options));
  return stub;
}

PropogationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetPropogation_(PropogationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PropogationService::Stub::GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::satproto::PropogationReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::satproto::PropogationRequest, ::satproto::PropogationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPropogation_, context, request, response);
}

void PropogationService::Stub::async::GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::satproto::PropogationRequest, ::satproto::PropogationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropogation_, context, request, response, std::move(f));
}

void PropogationService::Stub::async::GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropogation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>* PropogationService::Stub::PrepareAsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::satproto::PropogationReply, ::satproto::PropogationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPropogation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>* PropogationService::Stub::AsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPropogationRaw(context, request, cq);
  result->StartCall();
  return result;
}

PropogationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PropogationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PropogationService::Service, ::satproto::PropogationRequest, ::satproto::PropogationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PropogationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::satproto::PropogationRequest* req,
             ::satproto::PropogationReply* resp) {
               return service->GetPropogation(ctx, req, resp);
             }, this)));
}

PropogationService::Service::~Service() {
}

::grpc::Status PropogationService::Service::GetPropogation(::grpc::ServerContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace satproto
#include <grpcpp/ports_undef.inc>

