// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/v2/sat.proto
#ifndef GRPC_api_2fv2_2fsat_2eproto__INCLUDED
#define GRPC_api_2fv2_2fsat_2eproto__INCLUDED

#include "api/v2/sat.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace satproto {

class PropogationService final {
 public:
  static constexpr char const* service_full_name() {
    return "satproto.PropogationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::satproto::PropogationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>> AsyncGetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>>(AsyncGetPropogationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>> PrepareAsyncGetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>>(PrepareAsyncGetPropogationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>* AsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::satproto::PropogationReply>* PrepareAsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::satproto::PropogationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>> AsyncGetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>>(AsyncGetPropogationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>> PrepareAsyncGetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>>(PrepareAsyncGetPropogationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, std::function<void(::grpc::Status)>) override;
      void GetPropogation(::grpc::ClientContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>* AsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::satproto::PropogationReply>* PrepareAsyncGetPropogationRaw(::grpc::ClientContext* context, const ::satproto::PropogationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPropogation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPropogation(::grpc::ServerContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPropogation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPropogation(::grpc::ServerContext* context, ::satproto::PropogationRequest* request, ::grpc::ServerAsyncResponseWriter< ::satproto::PropogationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPropogation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPropogation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::satproto::PropogationRequest, ::satproto::PropogationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::satproto::PropogationRequest* request, ::satproto::PropogationReply* response) { return this->GetPropogation(context, request, response); }));}
    void SetMessageAllocatorFor_GetPropogation(
        ::grpc::MessageAllocator< ::satproto::PropogationRequest, ::satproto::PropogationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::satproto::PropogationRequest, ::satproto::PropogationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPropogation(
      ::grpc::CallbackServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetPropogation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPropogation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPropogation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPropogation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPropogation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPropogation(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPropogation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPropogation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPropogation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::satproto::PropogationRequest, ::satproto::PropogationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::satproto::PropogationRequest, ::satproto::PropogationReply>* streamer) {
                       return this->StreamedGetPropogation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPropogation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPropogation(::grpc::ServerContext* /*context*/, const ::satproto::PropogationRequest* /*request*/, ::satproto::PropogationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPropogation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::satproto::PropogationRequest,::satproto::PropogationReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPropogation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPropogation<Service > StreamedService;
};

}  // namespace satproto


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_api_2fv2_2fsat_2eproto__INCLUDED
